"""empty message

Revision ID: ad0041c4b2e8
Revises: b47e3dac5e8b
Create Date: 2021-07-14 16:04:02.919881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0041c4b2e8'
down_revision = 'b47e3dac5e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product', sa.String(), nullable=False))
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cart', 'product')
    # ### end Alembic commands ###
